name: Compile and upload résumé PDF
on:
    push:
        branches:
            - "main"
        paths:
            - "Yu_Aaron_Resume.tex"
            - "index.html"
            - ".github/workflows/**"
            - "resume/**"
            - "resources/**"
    pull_request:
        branches:
            - "main"
        paths:
            - "Yu_Aaron_Resume.tex"
            - "index.html"
            - ".github/workflows/**"
            - "resume/**"
            - "resources/**"

jobs:
    build_latex:
        runs-on: ubuntu-latest
        container:
            image: danteev/texlive:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: Yu_Aaron_Resume.tex
                  latexmk_use_xelatex: true
                  extra_fonts: |
                    ./fonts/*.ttf

            - name: Post Processing
              run: |
                  mkdir build 
                  cp *.pdf build/ 
                  cp index.html build/
                  
            - name: Git Add
              run: |
                git config --global --add safe.directory /__w/resume/resume
                git add Yu_Aaron_Resume.pdf
              
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.4.2
              with:
                  BRANCH: gh-pages
                  FOLDER: build
                  CLEAN: true
